name: '🎨 Style Suggestion'
description: Have any ideas for improving the style or design of RefactorMate? Share your suggestions here!
title: '[Style]: <brief description of the suggestion>'
labels:
  - 'style'
  - 'enhancement'
  - 'priority: medium'
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of your style or design suggestion.
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Why do you believe this style change is important or necessary?
    validations:
      required: true

  - type: textarea
    id: implementation_details
    attributes:
      label: Implementation Details (optional)
      description: Any ideas or suggestions on how this style change could be implemented?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots or mockups if applicable
    validations:
      required: false

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: 'Checklist'
      options:
        - label: 'I have starred the repository'
          required: true
        - label: 'I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)'
          required: true
        - label: 'I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)'
          required: true
        - label: "I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)"
          required: true
        - label: 'I am willing to work on this issue (optional)'
          required: false
