name: 🐞 Bug Report
description: Report an issue to help us improve the project.
title: '[BUG]: <brief description>'
labels:
  - 'bug'
  - 'goal: fix'
  - 'priority: medium'
body:
  - type: textarea
    attributes:
      label: Description
      description: >
        A brief description of the issue or bug you are facing. 
        Include steps to reproduce the issue, what you expected to happen, and what actually happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >
        Detailed steps to reproduce the bug. Please be as specific as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: >
        Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: >
        Describe what actually happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: >
        If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: >
        Any other information or context about the problem.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Browser
      description: >
        What browser are you experiencing the issue on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true

- type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: 'Checklist'
      options:
        - label: 'I have starred the repository'
          required: true
        - label: 'I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)'
          required: true
        - label: 'I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)'
          required: true
        - label: 'I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)'
          required: true
        - label: 'I am willing to work on this issue (optional)'
          required: false
